[package]
name = "hidden-watermark-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
hidden_watermark = "0.1.8"

[profile.release]
opt-level = "s"
